site_name: OpenStreetMap

repo_name: '2023.1-OpenStreetMap'
repo_url: https://github.com/Interacao-Humano-Computador/2023.1-OpenStreetMap/
site_url: https://interacao-humano-computador.github.io/2023.1-OpenStreetMap/
edit_uri: edit/main/docs/

copyright: Copyright & copy; 2023 OpenStreetMap

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js


theme:
  custom_dir: overrides
  name: material
  language: pt-BR
  logo: assets/imagens/logo.png
  favicon: assets/imagens/logo.png

  icon:
    repo: fontawesome/brands/github

  features:
    - toc.integrate
    - toc.follow
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.instant
    - navigation.top

  hide: 
    - 
    
  extra:
    social:
      - icon: fontawesome/brands/mastodon
        link: https://fosstodon.org/@squidfunk
    
  plugins: 
    - search:
        lang: pt-BR

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: orange
      toggle:
        icon: custom-icons/contrast-light
        name: Modo Claro
    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light green
      accent: yellow
      toggle:
        icon: custom-icons/contrast-dark
        name: Modo Escuro

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons 

nav:
  - Home: index.md
  - Planejamento: 
    - Sites Analisados: Planejamento/Sites_Analisados.md
    - Site Escolhido: Planejamento/Site_Escolhido.md
    - Processo de Design: Planejamento/Processo_Design.md
    - Metodologia: Planejamento/Metodologias.md
    - Ferramentas: Planejamento/Ferramentas.md
    - Cronograma: Planejamento/Cronograma.md
    - Cronograma Realizado: Planejamento/Cronograma_Realizado.md
    - Heatmap: Planejamento/heatmap.md
    - Aspectos Éticos: Planejamento/Aspectos_Eticos.md
  - Análise de Requisitos:
    - Perfil do usuário: AnaliseRequisitos/perfil_usuario.md
    - Personas: AnaliseRequisitos/Personas.md
    - Cenários: AnaliseRequisitos/cenarios.md
    - Análise de Tarefas: AnaliseRequisitos/analiseTarefas.md
    - Princípios Gerais do Projeto: AnaliseRequisitos/principiosGerais.md
    - Metas de Usabilidade: AnaliseRequisitos/Metas_usabilidade.md
    - Guia de estilo: AnaliseRequisitos/guia-de-estilo.md
  - Design, Avaliação e Desenvolvimento:
    - 1° Nível:
      - Análise de Tarefas:
        - Planejamento da Análise de Tarefas: DesignAvaliação/analisetarefas/planejamento_analise_tarefa.md
        - Planejamento do Relato de Resultados: DesignAvaliação/analisetarefas/planejamento_relato.md
        - Relato dos Resultados: DesignAvaliação/analisetarefas/relatoresultado.md
      - StoryBoard: 
        - Planejamento da Avaliação do Storyboard: DesignAvaliação/storyboard/planejamento_storyboard.md
        - Planejamento do Relato de Resultados: DesignAvaliação/storyboard/planejamento_relato.md
        - Relato do Resultados: DesignAvaliação/storyboard/relatoresultados.md
    - 2° Nível:
      - Prototipação de Papel:
        - Planejamento da Avaliação do Protótipo de Papel: DesignAvaliação/Prototipopapel/planejamento_Prototipopapel.md
        - Planejamento do Relato dos Resultados da Avaliação do Protótipo de Papel: DesignAvaliação/Prototipopapel/planejamento-relato.md
        - Protótipo de Papel: DesignAvaliação/Prototipopapel/prototipos.md
        - Relato dos Resultados da Avaliação do Protótipo de Baixa Fidelidade: DesignAvaliação/Prototipopapel/relatos.md
    - 3º Nível:
      - Protótipo de Alta Fidelidade:
        - Planejamento da Avaliação do Protótipo de Alta Fidelidade: DesignAvaliação/PrototipoAltaFidelidade/planejamentoAltaFidelidade.md
        - Planejamento da Avaliação do Relato dos Resultados da Avaliação do Protótipo de Alta Fidelidade: DesignAvaliação/PrototipoAltaFidelidade/planejamento_relato.md
        - Protótipo de Alta Fidelidade: DesignAvaliação/PrototipoAltaFidelidade/prototipo-alta.md
        - Relato dos Resultados: DesignAvaliação/PrototipoAltaFidelidade/relatos.md
  - Verificação:
    - OpenStreetMap: 
      - Planejamento Geral: Verificacao/OpenStreetMap/0planejamento-geral.md
      - Entrega 1:
        - Planejamento: Verificacao/OpenStreetMap/Entrega1/0planejamento.md
        - Cronograma Planejado: Verificacao/OpenStreetMap/Entrega1/1CronogramaPlanejado.md
        - Cronograma Realizado: Verificacao/OpenStreetMap/Entrega1/2CronogramaRealizado.md
        - Ferramentas: Verificacao/OpenStreetMap/Entrega1/3Ferramentas.md
        - Metodologias: Verificacao/OpenStreetMap/Entrega1/4Metodologia.md
        - Sites Analisados: Verificacao/OpenStreetMap/Entrega1/5SitesAnalisados.md
      - Entrega 2: 
        - Planejamento: Verificacao/OpenStreetMap/Entrega2/0planejamento.md
        - Perfil de Usuário: Verificacao/OpenStreetMap/Entrega2/Perfil-de-Usuario.md
        - Personas: Verificacao/OpenStreetMap/Entrega2/personas.md
        - Cenários: Verificacao/OpenStreetMap/Entrega2/cenarios.md
        - Aspectos Éticos: Verificacao/OpenStreetMap/Entrega2/Aspectos-Eticos.md
        - Análise de Tarefas: Verificacao/OpenStreetMap/Entrega2/analise_tarefas.md
      - Entrega 3:
        - Planejamento: Verificacao/OpenStreetMap/Entrega3/0planejamento.md
        - Princípios Gerais: Verificacao/OpenStreetMap/Entrega3/principios_gerais.md
        - Guia de Estilo: Verificacao/OpenStreetMap/Entrega3/guia-estilo.md
        - Metas de usabilidade: Verificacao/OpenStreetMap/Entrega3/MetasDeUsabilidade.md
      - Entrega 4:
        - Planejamento: Verificacao/OpenStreetMap/Entrega4/0planejamento.md
        - Planejamento da Avaliação da Análise de Tarefas: Verificacao/OpenStreetMap/Entrega4/Planejamento-Avaliacao-AnaliseTarefas.md
        - Planejamento da Avaliação do Storyboard: Verificacao/OpenStreetMap/Entrega4/Planejamento-Avaliacao-sotoryboard.md
        - Planejamento do Relato da AnaliseTarefas: Verificacao/OpenStreetMap/Entrega4/Planejamento-Relato-Resultados.md
        - Planejamento do Relato do StoryBoard: Verificacao/OpenStreetMap/Entrega4/Planejamento-Relato-Storyboard.md

      - Entrega 5:
        - Planejamento: Verificacao/OpenStreetMap/Entrega5/0planejamento.md
        - Relato dos Resultados do Storyboard: Verificacao/OpenStreetMap/Entrega5/1_verificacao_relato_dos_resultados_do_storyboard.md
        - Relato dos Resultados da Análise de Tarefas: Verificacao/OpenStreetMap/Entrega5/2_verificacao_relato_dos_resultados_da_analise_de_tarefas.md
        - Planejamento da Avaliação do Protótipo de Papel: Verificacao/OpenStreetMap/Entrega5/3_verificacao_planejamento_da_avaliacao_do_prototipo_de_papel.md
        - Planejamento do Relato de Resultados da Avaliação do Protótipo de Papel: Verificacao/OpenStreetMap/Entrega5/4_verificacao_planejamento_do_relato_de_resultados_da_avaliacao_do_prototipo_de_papel.md 
      
      - Entrega 7:
        - Planejamento: Verificacao/OpenStreetMap/Entrega7/0planejamento.md 
        - Planejamento da Avaliação do Protótipo de Alta Fidelidade: Verificacao/OpenStreetMap/Entrega7/2_verificacao_planejamento_da_avaliacao_do_prototipo_de_alta_fidelidade.md
        - Planejamento da Avaliação do Relato dos Resultados da Avaliação do Protótipo de Alta Fidelidade: Verificacao/OpenStreetMap/Entrega7/3_verificacao_planejamento_da_avaliacao_do_relato_dos_resultados_da_avaliacao_do_prototipo_de_alta_fidelidade.md
        - Relato dos resultados da avaliação do Protótipo de baixa fidelidade: Verificacao\OpenStreetMap\Entrega7\1_verificacao_relato_dos_resultados_da_avaliacao_do_prototipo_de_baixa_fidelidade.md
    - Grupo 5: 
      - Padronização da Verificação: Verificacao/grupo5/padronizacao_verificacao.md
      - Ponto de Controle 1°: Verificacao/grupo5/ponto1.md
      - Ponto de Controle 2°: Verificacao/grupo5/ponto2.md
      - Ponto de Controle 3°: Verificacao/grupo5/ponto3.md
      - Ponto de Controle 4°: Verificacao/grupo5/ponto4.md
      - Ponto de Controle 5°: Verificacao/grupo5/ponto5.md
  - Atas: 
    - Reunião 1: Atas/Reuniao01.md
    - Reunião 2: Atas/Reuniao02.md
    - Reunião 3: Atas/Reuniao03.md
    - Reunião 4: Atas/Reuniao04.md
    - Reunião 5: Atas/Reuniao05.md
    - Reunião 6: Atas/Reuniao06.md
    - Reunião 7: Atas/Reuniao07.md
  - Guia: 
    - Guia: Guia/Mkdocs.md
  - Entregas: Apresentações/Apresentacoes.md
  - Entrega Final: EntregaFinal/entrega-final.md

  
