site_name: OpenStreetMap

repo_name: '2023.1-OpenStreetMap'
repo_url: https://github.com/Interacao-Humano-Computador/2023.1-OpenStreetMap
site_url: https://2023.1-OpenStreetMap.com/

copyright: Copyright & copy; 2023 OpenStreetMap

theme:
  name: material
  language: pt-BR
  logo: assets/imagens/logo.png
  favicon: assets/imagens/logo.png

  icon:
    repo: fontawesome/brands/github

  features:
    - toc.integrate 
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer

  hide: 
    - 
    
  extra:
    social:
      - icon: fontawesome/brands/mastodon
        link: https://fosstodon.org/@squidfunk
    
  plugins: 
    - search:
        lang: pt-BR

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: orange
      toggle:
        icon: material/lightbulb
        name: Modo Claro
    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light green
      accent: yellow
      toggle:
        icon: material/lightbulb-outline
        name: Modo Escuro
  

nav:
  - Home: index.md
  - Planejamento: 
    - Site Escolhido: Planejamento/Site Escolhido.md
    - Sites Analisados: Planejamento/Sites Analisados.md
    - Processo de Design: Planejamento/Processo Design.md
    - Metodologia: Planejamento/Metodologias.md
    - Ferramentas: Planejamento/Ferramentas.md
    - Cronograma: Planejamento/Cronograma.md
    - Cronograma Realizado: Planejamento/Cronograma_Realizado.md
  - Apresentações:
    - Apresentação 1 : Apresentações/Apresentacao 01.md
  - Atas:
    - Atas/Reuniao 01.md
    - Atas/Reuniao 02.md
    - Atas/Reuniao 03.md
  - Guia: 
    - Guia/Mkdocs.md
  